import { AppHeader, Brand } from "@/components/AppHeader";
import { useLanguage } from "@/i18n";
import { trpc } from "@/lib/trpc";
import type { LocalizedText } from "@shared/simulation/types";
import { Award, CheckCircle2, Copy, Download, Loader2, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { useParams } from "wouter";

const local = (value: unknown, language: "en" | "ar") => (value as LocalizedText | undefined)?.[language] ?? "CareerSim Gulf";

export default function Certificate() {
  const { code } = useParams<{ code: string }>();
  const { language } = useLanguage();
  const query = trpc.sharing.certificate.useQuery({ code });
  const copy = language === "ar" ? { loading: "جارٍ التحقق من الشهادة…", certificate: "شهادة إتمام محاكاة وظيفية", certifies: "تشهد CareerSim Gulf بأن", completed: "قد أتم بنجاح", score: "النتيجة", date: "تاريخ الإتمام", verification: "رمز التحقق", verify: "تم التحقق من هذه الشهادة", print: "طباعة أو حفظ PDF", copy: "نسخ الرابط", disclaimer: "تمثل هذه الشهادة إتمام محاكاة وظيفية ولا تشكل اعتماداً أكاديمياً." } : { loading: "Verifying certificate…", certificate: "Job Simulation Completion Certificate", certifies: "CareerSim Gulf certifies that", completed: "has successfully completed", score: "Score", date: "Completion date", verification: "Verification code", verify: "This certificate is verified", print: "Print or save PDF", copy: "Copy link", disclaimer: "This certificate represents completion of a job simulation and does not constitute academic accreditation." };
  if (query.isLoading) return <div className="grid min-h-screen place-items-center"><Loader2 className="h-6 w-6 animate-spin text-teal-700" /></div>;
  if (!query.data) return <div className="grid min-h-screen place-items-center bg-slate-50 p-5"><div className="rounded-2xl bg-white p-8 text-center shadow-xl"><ShieldCheck className="mx-auto h-8 w-8 text-slate-400" /><p className="mt-4 text-sm text-slate-600">Certificate not found.</p></div></div>;
  const { certificate, result, simulation, user } = query.data;
  const date = new Intl.DateTimeFormat(language === "ar" ? "ar-SA" : "en-GB", { dateStyle: "long" }).format(new Date(certificate.issuedAt));
  const share = async () => { await navigator.clipboard.writeText(window.location.href); toast.success(language === "ar" ? "تم نسخ الرابط" : "Link copied"); };
  return <div className="min-h-screen bg-[#edf4f3]"><div className="print:hidden"><AppHeader /></div><main className="container py-8 sm:py-12"><div className="print:hidden mb-5 flex flex-wrap justify-end gap-2"><button type="button" onClick={share} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-bold text-slate-700"><Copy className="h-3.5 w-3.5" />{copy.copy}</button><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-3 py-2.5 text-xs font-bold text-white"><Download className="h-3.5 w-3.5" />{copy.print}</button></div><section className="relative overflow-hidden border-[10px] border-teal-800 bg-[#fffdf8] px-7 py-10 shadow-2xl shadow-slate-900/15 sm:px-14 sm:py-16"><div className="absolute inset-4 border border-teal-800/20" /><div className="relative mx-auto max-w-3xl text-center"><div className="flex justify-center"><Brand /></div><p className="mt-10 text-xs font-bold uppercase tracking-[.2em] text-teal-700">{copy.certificate}</p><div className="mx-auto mt-5 h-px w-16 bg-amber-500" /><p className="mt-9 text-sm text-slate-500">{copy.certifies}</p><h1 className="mt-3 font-display text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">{user.name ?? "CareerSim Student"}</h1><p className="mt-9 text-sm text-slate-500">{copy.completed}</p><h2 className="mt-3 font-display text-2xl font-bold text-teal-800 sm:text-3xl">{local(simulation.title, language)}</h2><p className="mt-2 text-sm text-slate-600">{local(simulation.company, language)}</p><div className="mx-auto mt-10 grid max-w-xl gap-4 border-y border-slate-200 py-5 sm:grid-cols-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{copy.score}</p><p className="mt-1 text-xl font-bold text-teal-800">{result.totalScore} / 100</p></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{copy.date}</p><p className="mt-1 text-sm font-bold text-slate-700">{date}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{copy.verification}</p><p className="mt-1 text-sm font-bold text-slate-700">{certificate.verificationCode}</p></div></div><div className="mt-8 flex justify-center"><span className="inline-flex items-center gap-2 rounded-full bg-teal-50 px-3 py-2 text-xs font-bold text-teal-800"><CheckCircle2 className="h-3.5 w-3.5" />{copy.verify}</span></div><p className="mt-10 text-xs leading-5 text-slate-400">{copy.disclaimer}</p></div><Award className="absolute -bottom-9 -right-8 h-40 w-40 text-teal-800/5" /></section></main></div>;
}
