import { AppHeader } from "@/components/AppHeader";
import { PersonalizedOnboardingDialog } from "@/components/PersonalizedOnboardingDialog";
import { CatalogCardItem, SimulationCard } from "@/components/SimulationCard";
import { useLanguage } from "@/i18n";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BarChart3, BriefcaseBusiness, CheckCircle2, FileSearch, FolderOpen, Loader2, Mail, Sparkles, Trophy } from "lucide-react";
import { useLocation } from "wouter";
import { useEffect, useState } from "react";

const workspaceItems = [{ Icon: Mail, label: "Inbox" }, { Icon: FolderOpen, label: "Files" }, { Icon: BarChart3, label: "Data" }];

export default function Home() {
  const { t, language } = useLanguage();
  const [, setLocation] = useLocation();
  const [onboardingOpen, setOnboardingOpen] = useState(false);
  const catalog = trpc.catalog.list.useQuery();
  useEffect(() => {
    if (sessionStorage.getItem("careersim-personalized-onboarding") === "1") {
      sessionStorage.removeItem("careersim-personalized-onboarding");
      setOnboardingOpen(true);
    }
  }, []);
  const steps = [
    { icon: BriefcaseBusiness, en: "Choose a career", ar: "اختر مساراً مهنياً" },
    { icon: Mail, en: "Enter the workplace", ar: "ادخل بيئة العمل" },
    { icon: FileSearch, en: "Complete real tasks", ar: "أنجز مهام واقعية" },
    { icon: BarChart3, en: "Get evaluated", ar: "احصل على تقييم" },
    { icon: Trophy, en: "Build your portfolio", ar: "ابنِ ملفك المهني" },
  ];
  const paths = [{ en: "Technology", ar: "التقنية" }, { en: "Business", ar: "الأعمال" }, { en: "Finance", ar: "المالية" }, { en: "Marketing", ar: "التسويق" }, { en: "Engineering", ar: "الهندسة" }, { en: "Science", ar: "العلوم" }];
  return <div className="min-h-screen overflow-hidden bg-[#f8fafc]"><AppHeader transparent /><main>
    <section className="relative isolate border-b border-slate-200 bg-[radial-gradient(circle_at_78%_12%,rgba(20,184,166,.14),transparent_32%),radial-gradient(circle_at_20%_5%,rgba(14,116,144,.1),transparent_28%),#f8fafc]"><div className="container grid min-h-[630px] items-center gap-12 py-16 lg:grid-cols-[1.06fr_.94fr] lg:py-20"><div className="relative z-10"><span className="inline-flex items-center gap-2 rounded-full border border-teal-100 bg-white px-3 py-1.5 text-xs font-bold tracking-wide text-teal-800 shadow-sm"><Sparkles className="h-3.5 w-3.5" />{t.home.eyebrow}</span><h1 className="mt-7 max-w-3xl font-display text-5xl font-bold leading-[0.99] tracking-[-0.045em] text-slate-950 sm:text-6xl lg:text-7xl">{t.home.titleLead}<span className="block text-teal-700">{t.home.titleAccent}</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">{t.home.description}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={() => setOnboardingOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3.5 text-sm font-bold text-white shadow-xl shadow-slate-900/15 transition hover:bg-teal-800 active:scale-[0.98]">{t.home.primary}<ArrowRight className="h-4 w-4 rtl:rotate-180" /></button><button type="button" onClick={() => setLocation("/catalog")} className="inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white px-5 py-3.5 text-sm font-bold text-slate-700 transition hover:border-teal-200 hover:bg-teal-50 active:scale-[0.98]">{t.home.secondary}</button></div><p className="mt-7 flex items-center gap-2 text-xs font-medium text-slate-500"><CheckCircle2 className="h-4 w-4 text-teal-700" />{t.home.proof}</p></div>
      <div className="relative mx-auto w-full max-w-[480px]"><div className="absolute -inset-8 rounded-full bg-teal-300/20 blur-3xl" /><div className="relative rounded-[2rem] border border-white/60 bg-white/80 p-4 shadow-[0_30px_100px_-35px_rgba(15,23,42,.38)] backdrop-blur-xl"><div className="flex items-center justify-between rounded-2xl bg-slate-950 px-4 py-3 text-white"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-teal-400 text-slate-950"><BriefcaseBusiness className="h-3.5 w-3.5" /></span><span className="text-sm font-bold">Gulf Retail Group</span></div><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] font-semibold text-teal-100">BI Workspace</span></div><div className="mt-4 grid grid-cols-[82px_1fr] gap-3"><aside className="rounded-xl bg-slate-50 p-2"><p className="px-2 py-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">Workspace</p>{workspaceItems.map(({ Icon, label }) => <div key={label} className={`mt-1 flex items-center gap-2 rounded-lg px-2 py-2 text-[10px] font-semibold ${label === "Data" ? "bg-teal-700 text-white" : "text-slate-500"}`}><Icon className="h-3 w-3" />{label}</div>)}</aside><div className="space-y-3"><div className="rounded-xl border border-slate-100 p-3"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold text-slate-950">Urgent — Riyadh sales performance</p><p className="mt-1 text-[9px] text-slate-400">from Sara Al-Harbi · 09:15</p></div><span className="h-2 w-2 rounded-full bg-teal-500" /></div><p className="mt-3 text-[9px] leading-4 text-slate-500">Investigate the main drivers behind the decline before tomorrow&apos;s management meeting.</p></div><div className="rounded-xl border border-slate-100 p-3"><div className="mb-3 flex justify-between"><p className="text-[10px] font-bold text-slate-950">Revenue by month</p><p className="text-[9px] font-bold text-red-500">−31.4%</p></div><div className="flex h-20 items-end gap-2">{[42,48,53,51,55,57,56,59,61,42,38,35].map((height, index) => <span key={index} style={{ height: `${height}%` }} className={`w-full rounded-t-sm ${index > 8 ? "bg-teal-600" : "bg-teal-200"}`} />)}</div></div></div></div></div><div className="absolute -bottom-5 -left-6 rounded-xl border border-slate-100 bg-white p-3 shadow-lg"><p className="text-[10px] font-bold text-slate-400">CURRENT OBJECTIVE</p><p className="mt-1 text-xs font-bold text-slate-900">Find the main driver</p></div></div></div></section>
    <section className="border-b border-slate-200 bg-white"><div className="container py-16"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-700">{t.home.how}</p><h2 className="mt-4 max-w-md font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">{t.home.howTitle}</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{steps.map(({ icon: Icon, en, ar }, index) => <div key={en} className="relative rounded-2xl border border-slate-200 bg-slate-50 p-4"><span className="text-xs font-black text-teal-700">0{index + 1}</span><Icon className="mt-6 h-5 w-5 text-slate-900" /><p className="mt-3 text-sm font-bold text-slate-900">{language === "ar" ? ar : en}</p></div>)}</div></div></div></section>
    <section className="container py-16 lg:py-20"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-700">{t.home.paths}</p><h2 className="mt-4 font-display text-3xl font-bold tracking-tight text-slate-950">{t.home.workplace}</h2></div><button type="button" onClick={() => setLocation("/catalog")} className="inline-flex items-center gap-2 text-sm font-bold text-teal-700 hover:text-teal-800">{t.home.secondary}<ArrowRight className="h-4 w-4 rtl:rotate-180" /></button></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{paths.map((path, index) => <div key={path.en} className="group flex items-center justify-between rounded-2xl border border-slate-200 bg-white px-5 py-5 transition hover:-translate-y-0.5 hover:border-teal-200 hover:shadow-lg hover:shadow-slate-900/5"><span className="font-display text-lg font-bold text-slate-900">{language === "ar" ? path.ar : path.en}</span><span className={`grid h-9 w-9 place-items-center rounded-xl ${index === 0 ? "bg-teal-700 text-white" : "bg-slate-100 text-slate-400"}`}><ArrowRight className="h-4 w-4 rtl:rotate-180" /></span></div>)}</div></section>
    <section className="bg-slate-950 py-16 text-white lg:py-20"><div className="container"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-200">{t.home.featured}</p><h2 className="mt-4 font-display text-3xl font-bold tracking-tight">{t.home.workplaceText}</h2></div><p className="max-w-sm text-sm leading-6 text-slate-400">{t.home.featuredText}</p></div><div className="mt-9 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{catalog.isLoading && <div className="col-span-full flex h-48 items-center justify-center"><Loader2 className="h-5 w-5 animate-spin text-teal-300" /></div>}{catalog.data?.slice(0, 3).map(item => <SimulationCard key={item.id} item={item as CatalogCardItem} featured={item.status === "published"} />)}</div></div></section>
  </main><footer className="bg-slate-950 pb-8 text-center text-xs text-slate-500">CareerSim Gulf · {t.home.banner}</footer><PersonalizedOnboardingDialog open={onboardingOpen} onOpenChange={setOnboardingOpen} /></div>;
}
