import { useLanguage } from "@/i18n";
import type { SalesRecord, SimulationTaskConfig } from "@shared/simulation/types";
import { CheckCircle2, ChevronRight, Lightbulb, Loader2, Send, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const strings = {
  en: { title: "Current assignment", objective: "Objective", resources: "Resources", deliverable: "Deliverable", hint: "Request a hint", hintLabel: "Hint", submit: "Submit response", submitted: "Submitted", branch: "Select a branch", evidence: "What evidence supports your choice?", metric: "Metric", dimension: "Group by", cause: "Primary driver", takeaway: "What does your chart show?", sources: "Select two evidence sources", response: "Your response", words: "words", recommendation: "Management recommendation", chart: "Preview", completion: "Assignment complete", next: "Move to next task" },
  ar: { title: "المهمة الحالية", objective: "الهدف", resources: "الموارد", deliverable: "المطلوب", hint: "اطلب تلميحاً", hintLabel: "تلميح", submit: "إرسال الإجابة", submitted: "تم الإرسال", branch: "اختر فرعاً", evidence: "ما الدليل الذي يدعم اختيارك؟", metric: "المقياس", dimension: "التجميع حسب", cause: "المحرك الرئيسي", takeaway: "ماذا يوضح مخططك؟", sources: "اختر مصدرين للأدلة", response: "إجابتك", words: "كلمات", recommendation: "توصية الإدارة", chart: "معاينة", completion: "اكتملت المهمة", next: "انتقل إلى المهمة التالية" },
};

const toStrings = (value: unknown): string[] => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
const inputMap = (input: Record<string, unknown>) => input as Record<string, unknown>;

export function TaskPanel({ task, records, existingResponse, onSubmit, pending, completed }: { task: SimulationTaskConfig; records: SalesRecord[]; existingResponse?: Record<string, unknown>; onSubmit: (response: Record<string, unknown>, hintLevel: number) => void; pending: boolean; completed: boolean }) {
  const { language, text } = useLanguage();
  const copy = strings[language];
  const [hintLevel, setHintLevel] = useState(0);
  const [branch, setBranch] = useState("");
  const [evidence, setEvidence] = useState("");
  const [metric, setMetric] = useState("Customers");
  const [dimension, setDimension] = useState("Month");
  const [cause, setCause] = useState("");
  const [sources, setSources] = useState<string[]>([]);
  const [response, setResponse] = useState("");
  const input = inputMap(task.input);
  const branches = useMemo(() => Array.from(new Set(records.map(record => record.branch))), [records]);
  useEffect(() => { const prior = existingResponse ?? {}; setHintLevel(0); setBranch(typeof prior.branch === "string" ? prior.branch : ""); setEvidence(typeof prior.evidence === "string" ? prior.evidence : typeof prior.rationale === "string" ? prior.rationale : ""); setMetric(typeof prior.metric === "string" ? prior.metric : "Customers"); setDimension(typeof prior.dimension === "string" ? prior.dimension : "Month"); setCause(typeof prior.cause === "string" ? prior.cause : typeof prior.choice === "string" ? prior.choice : ""); setSources(toStrings(prior.sources)); setResponse(typeof prior.response === "string" ? prior.response : ""); }, [task.id, existingResponse]);
  const chartData = useMemo(() => {
    const values = dimension === "Month" ? Array.from(new Set(records.map(record => record.month))) : Array.from(new Set(records.map(record => record.productCategory)));
    return values.map(value => ({ label: dimension === "Month" ? value.slice(5) : value, value: records.filter(record => (dimension === "Month" ? record.month : record.productCategory) === value && (branch ? record.branch === branch : true)).reduce((sum, record) => sum + (metric === "Customers" ? record.customers : metric === "Average Order Value" ? record.averageOrderValue : metric === "Marketing Spend" ? record.marketingSpend : record.revenue), 0) }));
  }, [branch, dimension, metric, records]);
  const selectedFileIds = toStrings(input.sources);
  const selectSource = (source: string) => setSources(current => current.includes(source) ? current.filter(item => item !== source) : current.length >= 2 ? current : [...current, source]);
  const submit = () => {
    if (task.type === "data_exploration") onSubmit({ branch, evidence }, hintLevel);
    else if (task.type === "visualization_builder") onSubmit({ metric, dimension, cause, takeaway: evidence }, hintLevel);
    else if (task.type === "written_insight") onSubmit({ sources, response }, hintLevel);
    else if (task.type === "single_choice") onSubmit({ choice: cause, rationale: evidence }, hintLevel);
    else onSubmit({ response }, hintLevel);
  };
  const canSubmit = task.type === "data_exploration" ? Boolean(branch && evidence.trim()) : task.type === "visualization_builder" ? Boolean(metric && dimension && cause && evidence.trim()) : task.type === "written_insight" ? Boolean(sources.length === 2 && response.trim()) : task.type === "single_choice" ? Boolean(cause) : Boolean(response.trim());
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex flex-col gap-4 border-b border-slate-100 pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-teal-700">{copy.title}</p><h1 className="mt-2 font-display text-2xl font-bold tracking-tight text-slate-950">{text(task.title)}</h1></div><span className="inline-flex w-fit rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-600">{task.estimatedMinutes} {language === "ar" ? "دقيقة" : "min"}</span></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="rounded-xl bg-teal-50 p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-teal-700">{copy.objective}</p><p className="mt-2 text-sm leading-6 text-slate-700">{text(task.objective)}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">{copy.deliverable}</p><p className="mt-2 text-sm leading-6 text-slate-700">{text(task.deliverable)}</p></div></div><p className="mt-6 text-sm leading-7 text-slate-700">{text(task.instructions)}</p><div className="mt-6 rounded-2xl border border-slate-100 p-4 sm:p-5">
    {task.type === "data_exploration" && <div className="grid gap-4"><label className="grid gap-2 text-sm font-bold text-slate-700">{copy.branch}<select value={branch} onChange={event => setBranch(event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal outline-none focus:border-teal-600"> <option value="">{copy.branch}</option>{branches.map(value => <option key={value}>{value}</option>)}</select></label><label className="grid gap-2 text-sm font-bold text-slate-700">{copy.evidence}<textarea value={evidence} onChange={event => setEvidence(event.target.value)} rows={4} className="rounded-xl border border-slate-200 p-3 text-sm font-normal outline-none focus:border-teal-600" /></label></div>}
    {task.type === "visualization_builder" && <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><div className="space-y-4"><label className="grid gap-2 text-sm font-bold text-slate-700">{copy.metric}<select value={metric} onChange={event => setMetric(event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal outline-none focus:border-teal-600">{toStrings(input.metrics).map(value => <option key={value}>{value}</option>)}</select></label><label className="grid gap-2 text-sm font-bold text-slate-700">{copy.dimension}<select value={dimension} onChange={event => setDimension(event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal outline-none focus:border-teal-600">{toStrings(input.dimensions).map(value => <option key={value}>{value}</option>)}</select></label><label className="grid gap-2 text-sm font-bold text-slate-700">{copy.branch}<select value={branch} onChange={event => setBranch(event.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal outline-none focus:border-teal-600"><option value="">{language === "ar" ? "كل الفروع" : "All branches"}</option>{branches.map(value => <option key={value}>{value}</option>)}</select></label></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-500">{copy.chart}</p><div className="mt-2 h-44"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><XAxis dataKey="label" tick={{ fontSize: 10 }} tickLine={false} axisLine={false} /><YAxis hide /><Tooltip /><Bar dataKey="value" fill="#0f766e" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></div><fieldset className="lg:col-span-2"><legend className="mb-2 text-sm font-bold text-slate-700">{copy.cause}</legend><div className="grid gap-2 sm:grid-cols-2">{toStrings(input.causes).map(value => <label key={value} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm transition ${cause === value ? "border-teal-600 bg-teal-50 text-teal-900" : "border-slate-200 text-slate-600"}`}><input type="radio" name={`cause-${task.id}`} value={value} checked={cause === value} onChange={() => setCause(value)} />{value}</label>)}</div></fieldset><label className="grid gap-2 text-sm font-bold text-slate-700 lg:col-span-2">{copy.takeaway}<textarea value={evidence} onChange={event => setEvidence(event.target.value)} rows={3} className="rounded-xl border border-slate-200 p-3 text-sm font-normal outline-none focus:border-teal-600" /></label></div>}
    {task.type === "written_insight" && <div><p className="text-sm font-bold text-slate-700">{copy.sources}</p><div className="mt-3 flex flex-wrap gap-2">{selectedFileIds.map(source => <button type="button" key={source} onClick={() => selectSource(source)} className={`rounded-lg border px-3 py-2 text-xs font-bold transition ${sources.includes(source) ? "border-teal-600 bg-teal-50 text-teal-800" : "border-slate-200 text-slate-600"}`}>{source.replaceAll("-", " ")}</button>)}</div><label className="mt-5 grid gap-2 text-sm font-bold text-slate-700">{copy.response}<textarea value={response} onChange={event => setResponse(event.target.value)} rows={7} className="rounded-xl border border-slate-200 p-3 text-sm font-normal outline-none focus:border-teal-600" /></label></div>}
    {task.type === "single_choice" && <div><div className="grid gap-2">{((input.options as Array<{ id: string; label: { en: string; ar: string } }>) ?? []).map(option => <label key={option.id} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-4 text-sm transition ${cause === option.id ? "border-teal-600 bg-teal-50 text-teal-900" : "border-slate-200 text-slate-600"}`}><input type="radio" name={`decision-${task.id}`} checked={cause === option.id} onChange={() => setCause(option.id)} /><span>{text(option.label)}</span></label>)}</div><label className="mt-5 grid gap-2 text-sm font-bold text-slate-700">{copy.evidence}<textarea value={evidence} onChange={event => setEvidence(event.target.value)} rows={3} className="rounded-xl border border-slate-200 p-3 text-sm font-normal outline-none focus:border-teal-600" /></label></div>}
    {task.type === "recommendation" && <div><label className="grid gap-2 text-sm font-bold text-slate-700">{copy.recommendation}<textarea value={response} onChange={event => setResponse(event.target.value)} rows={10} className="rounded-xl border border-slate-200 p-3 text-sm font-normal leading-6 outline-none focus:border-teal-600" /></label><p className="mt-2 text-xs text-slate-500">{response.trim() ? response.trim().split(/\s+/).length : 0} {copy.words}</p></div>}
  </div><div className="mt-5 flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:items-center sm:justify-between"><div>{hintLevel > 0 && <div className="rounded-xl bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-900"><span className="font-bold">{copy.hintLabel} {hintLevel}:</span> {text(task.hints[hintLevel - 1]!)}</div>}</div><div className="flex gap-2"><button type="button" disabled={hintLevel >= 3 || completed} onClick={() => setHintLevel(level => Math.min(3, level + 1))} className="inline-flex items-center justify-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-3 text-xs font-bold text-amber-800 transition hover:bg-amber-100 disabled:opacity-50"><Lightbulb className="h-3.5 w-3.5" />{copy.hint}</button><button type="button" disabled={!canSubmit || pending || completed} onClick={submit} className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-700 px-4 py-3 text-xs font-bold text-white shadow-sm transition hover:bg-teal-800 disabled:opacity-50">{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : completed ? <CheckCircle2 className="h-4 w-4" /> : <Send className="h-4 w-4" />}{completed ? copy.submitted : copy.submit}</button></div></div>{completed && <div className="mt-4 flex items-center gap-2 rounded-xl bg-teal-50 px-4 py-3 text-sm font-semibold text-teal-900"><Sparkles className="h-4 w-4" />{copy.completion}</div>}</section>;
}
