import { Skeleton } from "@/components/ui/skeleton";

export function PortfolioLoadingSkeleton() {
  return <div className="min-h-screen bg-[#f8fafc]" aria-busy="true" aria-label="Loading portfolio"><div className="h-[73px] border-b border-slate-200 bg-white" /><main className="container py-9 lg:py-14"><section className="rounded-[2rem] bg-slate-950 p-7 sm:p-10"><div className="grid gap-6 md:grid-cols-[1fr_auto]"><div><Skeleton className="h-7 w-36 rounded-full bg-white/10" /><Skeleton className="mt-6 h-11 w-72 max-w-full bg-white/15" /><Skeleton className="mt-4 h-4 w-full max-w-xl bg-white/10" /><Skeleton className="mt-2 h-4 w-4/5 max-w-lg bg-white/10" /></div><div className="flex items-center gap-3"><Skeleton className="h-14 w-14 rounded-2xl bg-teal-400/25" /><div><Skeleton className="h-5 w-32 bg-white/15" /><Skeleton className="mt-2 h-3 w-44 bg-white/10" /></div></div></div><div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-4 sm:flex sm:items-center sm:justify-between"><div><Skeleton className="h-3 w-24 bg-white/15" /><Skeleton className="mt-2 h-3 w-56 max-w-full bg-white/10" /></div><Skeleton className="mt-3 h-10 w-28 rounded-xl bg-white/15 sm:mt-0" /></div></section><div className="mt-8 grid gap-4 md:grid-cols-2">{[0, 1].map(index => <section key={index} className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><Skeleton className="h-3 w-24" /><Skeleton className="mt-3 h-7 w-3/5" /><Skeleton className="mt-3 h-4 w-2/5" /><Skeleton className="mt-6 h-14 w-full" /><div className="mt-5 flex gap-2"><Skeleton className="h-6 w-20 rounded-full" /><Skeleton className="h-6 w-24 rounded-full" /></div></section>)}</div></main></div>;
}

export function ResultsLoadingSkeleton() {
  return <div className="min-h-screen bg-[#f8fafc]" aria-busy="true" aria-label="Loading results"><div className="h-[73px] border-b border-slate-200 bg-white" /><main className="container py-9 lg:py-14"><section className="rounded-[2rem] bg-slate-950 p-7 sm:p-10 lg:p-12"><div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><Skeleton className="h-7 w-44 rounded-full bg-teal-300/15" /><Skeleton className="mt-6 h-12 w-80 max-w-full bg-white/15" /><Skeleton className="mt-5 h-4 w-full max-w-2xl bg-white/10" /><Skeleton className="mt-2 h-4 w-4/5 max-w-xl bg-white/10" /><div className="mt-8 flex gap-3"><Skeleton className="h-11 w-36 rounded-xl bg-teal-400/25" /><Skeleton className="h-11 w-36 rounded-xl bg-white/10" /></div></div><div className="grid place-items-center rounded-[1.5rem] border border-white/10 bg-white/5 p-6"><Skeleton className="h-40 w-40 rounded-full bg-teal-400/15" /><Skeleton className="mt-5 h-4 w-40 bg-white/15" /></div></div></section><div className="mt-7 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><section className="rounded-[1.75rem] border border-slate-200 bg-white p-6 sm:p-8"><Skeleton className="h-7 w-44" /><div className="mt-6 space-y-5">{[0, 1, 2, 3].map(index => <div key={index}><Skeleton className="h-4 w-28" /><Skeleton className="mt-2 h-2 w-full rounded-full" /></div>)}</div></section><section className="rounded-[1.75rem] border border-slate-200 bg-white p-6 sm:p-8"><Skeleton className="h-7 w-48" /><div className="mt-5 space-y-3">{[0, 1, 2].map(index => <Skeleton key={index} className="h-20 w-full rounded-xl" />)}</div></section></div></main></div>;
}
