-- CareerSim Gulf: Supabase PostgreSQL migration
-- Target project: gnarrdggnzmfgkiqzret
--
-- This migration is non-destructive: it creates only objects in the dedicated
-- `careersim` schema. It does not alter, drop, or read any existing public tables.
--
-- IMPORTANT AFTER RUNNING THIS FILE:
-- In Supabase Dashboard → Project Settings → API → Exposed schemas, add `careersim`.
-- The server will use the service-role key with db.schema = "careersim". Do not expose
-- the service-role key to the browser.

begin;

create schema if not exists careersim;

-- Keep the schema private by default. The CareerSim server reaches it with the
-- server-only service_role key; browser roles receive no database privileges.
revoke all on schema careersim from public;
revoke all on schema careersim from anon;
revoke all on schema careersim from authenticated;
grant usage on schema careersim to service_role;

create table if not exists careersim.users (
  id bigint generated by default as identity primary key,
  open_id varchar(64) not null unique,
  name text,
  email varchar(320),
  login_method varchar(64),
  role varchar(16) not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists careersim.profiles (
  id varchar(36) primary key,
  user_id bigint not null unique references careersim.users(id) on delete cascade,
  country varchar(80),
  university varchar(160),
  major varchar(160),
  graduation_year integer check (graduation_year between 1900 and 2200),
  career_interests jsonb not null default '[]'::jsonb check (jsonb_typeof(career_interests) = 'array'),
  preferred_language varchar(2) not null default 'en' check (preferred_language in ('en', 'ar')),
  public_slug varchar(80) not null unique,
  portfolio_is_public boolean not null default true,
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists careersim.simulations (
  id varchar(80) primary key,
  slug varchar(120) not null unique,
  config_version varchar(32) not null,
  status varchar(16) not null default 'published' check (status in ('draft', 'published', 'archived')),
  title jsonb not null check (jsonb_typeof(title) = 'object'),
  company jsonb not null check (jsonb_typeof(company) = 'object'),
  industry jsonb not null check (jsonb_typeof(industry) = 'object'),
  category varchar(64) not null,
  difficulty varchar(16) not null check (difficulty in ('beginner', 'intermediate', 'advanced')),
  estimated_minutes integer not null check (estimated_minutes > 0),
  skills jsonb not null default '[]'::jsonb check (jsonb_typeof(skills) = 'array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists careersim.simulation_sessions (
  id varchar(36) primary key,
  user_id bigint not null references careersim.users(id) on delete cascade,
  simulation_id varchar(80) not null references careersim.simulations(id) on delete restrict,
  config_version varchar(32) not null,
  status varchar(16) not null default 'active' check (status in ('active', 'completed', 'abandoned')),
  current_task_id varchar(80),
  progress_percent integer not null default 0 check (progress_percent between 0 and 100),
  hint_usage jsonb not null default '{}'::jsonb check (jsonb_typeof(hint_usage) = 'object'),
  started_at timestamptz not null default now(),
  last_active_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists careersim.task_submissions (
  id varchar(36) primary key,
  session_id varchar(36) not null references careersim.simulation_sessions(id) on delete cascade,
  task_id varchar(80) not null,
  task_type varchar(48) not null,
  response jsonb not null check (jsonb_typeof(response) = 'object'),
  hint_level integer not null default 0 check (hint_level >= 0),
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, task_id)
);

create table if not exists careersim.task_scores (
  id varchar(36) primary key,
  submission_id varchar(36) not null unique references careersim.task_submissions(id) on delete cascade,
  session_id varchar(36) not null references careersim.simulation_sessions(id) on delete cascade,
  task_id varchar(80) not null,
  score integer not null check (score >= 0),
  max_score integer not null check (max_score > 0 and score <= max_score),
  skill_scores jsonb not null default '{}'::jsonb check (jsonb_typeof(skill_scores) = 'object'),
  criteria jsonb not null default '[]'::jsonb check (jsonb_typeof(criteria) = 'array'),
  feedback_context jsonb not null default '[]'::jsonb check (jsonb_typeof(feedback_context) = 'array'),
  evaluated_at timestamptz not null default now(),
  unique (session_id, task_id)
);

create table if not exists careersim.simulation_results (
  id varchar(36) primary key,
  session_id varchar(36) not null unique references careersim.simulation_sessions(id) on delete cascade,
  user_id bigint not null references careersim.users(id) on delete cascade,
  simulation_id varchar(80) not null references careersim.simulations(id) on delete restrict,
  total_score integer not null check (total_score >= 0),
  max_score integer not null default 100 check (max_score > 0 and total_score <= max_score),
  skill_scores jsonb not null default '{}'::jsonb check (jsonb_typeof(skill_scores) = 'object'),
  feedback jsonb not null default '{"strengths": [], "improvements": [], "summary": ""}'::jsonb check (jsonb_typeof(feedback) = 'object'),
  completed_at timestamptz not null default now()
);

create table if not exists careersim.certificates (
  id varchar(36) primary key,
  result_id varchar(36) not null unique references careersim.simulation_results(id) on delete cascade,
  user_id bigint not null references careersim.users(id) on delete cascade,
  simulation_id varchar(80) not null references careersim.simulations(id) on delete restrict,
  verification_code varchar(40) not null unique,
  issued_at timestamptz not null default now()
);

create table if not exists careersim.portfolio_items (
  id varchar(36) primary key,
  user_id bigint not null references careersim.users(id) on delete cascade,
  result_id varchar(36) not null unique references careersim.simulation_results(id) on delete cascade,
  simulation_id varchar(80) not null references careersim.simulations(id) on delete restrict,
  summary text not null,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists careersim.simulation_events (
  id varchar(36) primary key,
  user_id bigint not null references careersim.users(id) on delete cascade,
  session_id varchar(36) references careersim.simulation_sessions(id) on delete cascade,
  event_type varchar(64) not null,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now()
);

-- Query patterns used by the tRPC simulation, result, certificate, and portfolio flows.
create index if not exists simulation_sessions_user_status_idx on careersim.simulation_sessions (user_id, status);
create index if not exists simulation_sessions_simulation_idx on careersim.simulation_sessions (simulation_id);
create index if not exists task_submissions_session_idx on careersim.task_submissions (session_id);
create index if not exists task_scores_session_idx on careersim.task_scores (session_id);
create index if not exists simulation_results_user_completed_idx on careersim.simulation_results (user_id, completed_at desc);
create index if not exists portfolio_items_user_public_idx on careersim.portfolio_items (user_id, is_public);
create index if not exists simulation_events_session_type_idx on careersim.simulation_events (session_id, event_type);

create or replace function careersim.set_updated_at()
returns trigger
language plpgsql
set search_path = careersim, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'users_set_updated_at') then
    create trigger users_set_updated_at before update on careersim.users for each row execute function careersim.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'profiles_set_updated_at') then
    create trigger profiles_set_updated_at before update on careersim.profiles for each row execute function careersim.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'simulations_set_updated_at') then
    create trigger simulations_set_updated_at before update on careersim.simulations for each row execute function careersim.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'task_submissions_set_updated_at') then
    create trigger task_submissions_set_updated_at before update on careersim.task_submissions for each row execute function careersim.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'portfolio_items_set_updated_at') then
    create trigger portfolio_items_set_updated_at before update on careersim.portfolio_items for each row execute function careersim.set_updated_at();
  end if;
end;
$$;

-- Defense in depth: enable RLS everywhere and grant no privileges to browser roles.
alter table careersim.users enable row level security;
alter table careersim.profiles enable row level security;
alter table careersim.simulations enable row level security;
alter table careersim.simulation_sessions enable row level security;
alter table careersim.task_submissions enable row level security;
alter table careersim.task_scores enable row level security;
alter table careersim.simulation_results enable row level security;
alter table careersim.certificates enable row level security;
alter table careersim.portfolio_items enable row level security;
alter table careersim.simulation_events enable row level security;

revoke all privileges on all tables in schema careersim from public, anon, authenticated;
revoke all privileges on all sequences in schema careersim from public, anon, authenticated;
grant select, insert, update, delete on all tables in schema careersim to service_role;
grant usage, select on all sequences in schema careersim to service_role;

alter default privileges in schema careersim revoke all on tables from public, anon, authenticated;
alter default privileges in schema careersim revoke all on sequences from public, anon, authenticated;
alter default privileges in schema careersim grant select, insert, update, delete on tables to service_role;
alter default privileges in schema careersim grant usage, select on sequences to service_role;

-- Refresh the Data API catalog after the owner exposes the `careersim` schema in Project Settings → API.
notify pgrst, 'reload schema';

commit;

-- Optional verification query. It does not modify data.
select table_name
from information_schema.tables
where table_schema = 'careersim'
order by table_name;
